model: mobilenetv3
pretrained: False
num_classes: 2

focal_gamma: 2
focal_alpha: null
T: 1.0

boundary_weight: 0.3
consistency_weight: 2.0

use_boundary_loss: true
use_consistency_loss: true

compile: null

optimizer:
  lr: 0.001
  weight_decay: 5.0e-4